[package]
name = "gambling_simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "gambling_simulator"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
rand = "0.8.5"
csv = "1.3.0"